slug: google-jax
description: |
  ## Why monitor Google JAX?
  Monitoring Google JAX is essential for optimizing performance, maintaining reliability, ensuring scalability, and continuously improving your machine learning applications.
  
  ## Comprehensive monitoring quickstart for Google JAX
  When you monitor Google JAX with New Relic, you can get comprehensive information about the performance efficiently, reliably, and in accordance with your performance goals.
  
  ## What’s included in this quickstart?
  New Relic Google JAX monitoring quickstart provides quality out-of-the-box reporting:
  - Performance Optimization: identify bottlenecks, inefficiencies, and performance issues in your JAX-based applications
  - Resource Management: Monitoring resource utilization (CPU, memory, GPU) ensures efficient use of hardware, prevents resource contention
  - Error Detection and Debugging: Monitoring allows you to capture and log errors, exceptions, and unexpected behavior during model training and inference
  - Security and Compliance: Monitoring will help you detect unusual or suspicious activity in your machine learning applications, which is essential for maintaining data security and regulatory compliance

summary: |
  Enhance the performance of your JAX-based applications by integrating them with New Relic for overall application monitoring and optimization.
icon: logo.png
level: New Relic
authors:
  - New Relic
  - Ramana Reddy
title: Google JAX
documentation:
  - name: Google JAX integration documentation
    description: |
     Integrate your Google JAX app and get your data into New Relic.
    url: https://github.com/newrelic-experimental/ml-performance-monitoring
dataSourceIds:
  -  bring-your-own-data
keywords:
  - Google JAX
  - machine learning
  - jax
