slug: tensorflow
description: |
  ## Why monitor TensorFlow?
  Monitoring TensorFlow applications helps you proactively ensure that your machine learning models perform as intended, remain reliable, adapt to changing conditions, maintain model quality, optimize resource usage, detect issues early, provide a positive user experience, and meet compliance and security requirements.
  
  ## Comprehensive monitoring quickstart for TensorFlow
  Integrating TensorFlow with New Relic gives us comprehensive information about TensorFlow applications, which is crucial for ensuring their performance, stability, and efficiency.
  
  ## What’s included in this quickstart?
  New Relic TensorFlow monitoring quickstart provides quality out-of-the-box reporting:
  - Performance Optimization: Detect performance issues in your TensorFlow models, such as bottlenecks, inefficiencies, and slowdowns
  - Cost Control: Control operational costs by identifying resource inefficiencies and optimizing infrastructure utilization
  - Security: Identify security vulnerabilities, such as adversarial attacks on your model, unauthorized access, or data leaks
  - Early issue detection: Get alerts when there are potential problems with your TensorFlow deployment so you can take action quickly

summary: |
  Improve the performance of your TensorFlow by using the New Relic TensorFlow quickstart.
icon: logo.png
level: New Relic
authors:
  - New Relic
  - Ramana Reddy
title: TensorFlow
documentation:
  - name: TensorFlow integration documentation
    description: |
     Integrate your TensorFlow with New Relic to get your data into New Relic.
    url: https://github.com/newrelic-experimental/ml-performance-monitoring
dataSourceIds:
  -  bring-your-own-data
keywords:
  - TensorFlow
  - machine learning
  - tensor
  - tensorflow serving
