slug: tensorflow
description: |
  ## Why monitor TensorFlow?
  Monitoring TensorFlow applications is a proactive approach to ensure that your machine learning models perform as intended, remain reliable, and adapt to changing conditions. It helps maintain model quality, optimize resource usage, detect issues early, and provide a positive user experience while meeting compliance and security requirements
  
  ## Comprehensive monitoring quickstart for TensorFlow
  By integrating TensorFlow with New Relic, we can get comprehensive information about TensorFlow applications that are crucial for ensuring their performance, stability, and efficiency.
  
  ## What’s included in this quickstart?
  New Relic TensorFlow monitoring quickstart provides quality out-of-the-box reporting:
  - Performance Optimization: Identify performance bottlenecks, inefficiencies, or slowdowns in your TensorFlow models
  - Cost Control: Control operational costs by identifying resource inefficiencies and optimizing infrastructure utilization
  - Security: Identify security vulnerabilities, such as adversarial attacks on your model, unauthorized access, or data leaks
  - Early issue detection: Get alerts when there are potential problems with your TensorFlow deployment so you can take action quickly

summary: |
  Enhance the performance of your TensorFlow applications by integrating with New Relic for overall application monitoring and optimization.
icon: logo.png
level: New Relic
authors:
  - New Relic
  - Ramana Reddy
title: TensorFlow
documentation:
  - name: TensorFlow integration documentation
    description: |
     Integrate your TensorFlow app and get your data into New Relic.
    url: https://github.com/newrelic-experimental/ml-performance-monitoring
dataSourceIds:
  -  bring-your-own-data
keywords:
  - TensorFlow
  - machine learning
  - tensor
  - tensorflow serving
