slug: lightgbm
description: |
  ## Why monitor LightGBM?
  Monitoring your LightGBM models is a critical aspect of the machine learning lifecycle. It helps you maintain model quality, optimize hyperparameters, ensure fairness, and make informed decisions throughout the model's development and deployment phases.

  ## Comprehensive monitoring quickstart for LightGBM
  LightGBM involves loading data, setting up LightGBM, monitoring training progress, and evaluating the model's performance.
  
  ## What’s included in this quickstart?
  New Relic LightGBM monitoring quickstart provides quality out-of-the-box reporting:
  - Wide range of machine learning tasks and applications
  - Its speed, memory efficiency, and scalability make it a valuable tool

summary: |
  By integrating your LightGBM models with New Relic application monitoring capabilities, you create a robust system for continuously monitoring, optimizing, and maintaining your machine learning models.
icon: logo.png
level: New Relic
authors:
  - New Relic
  - Ramana Reddy
title: LightGBM
documentation:
  - name: LightGBM integration documentation
    description: |
     Integrate your LightGBM app and get your data into New Relic.
    url: https://github.com/newrelic-experimental/ml-performance-monitoring
dataSourceIds:
  -  bring-your-own-data
keywords:
  -  LightGBM
  -  machine learning
  -  Gradient Boosting