id: github-for-codestream
displayName: GitHub for CodeStream
description: |
  GitHub is a code hosting platform for version control and collaboration. It lets developers and others work together on projects from anywhere. 

  With CodeStream you can create, review, and merge GitHub PRs without ever leaving your IDE. All with full source-tree and full file access, your favorite keybindings, and all the code intelligence embedded in your development environment.
install:
  primary:
    nerdlet:
      nerdletId: marketplace.install-data-source
      nerdletState:
        dataSourceId: github-for-codestream
      requiresAccount: false
icon: logo.png
