slug: cohere
description: |
  ## Why monitor Cohere?
  Monitored to ensure that it is performing as expected, to identify potential problems early on, to troubleshoot problems quickly, and to comply with regulations.
  
  ## Comprehensive monitoring quickstart for Cohere
  Our Cohere quickstart offers key metrics, Latency, throughput, and error rate. These metrics serve as valuable resources to help you optimize the performance of Cohere.
  
  ## What’s included in this quickstart?
  New Relic Cohere monitoring quickstart provides quality out-of-the-box reporting:
  - Dashboards (average tokens, LLM completion's details, chain's details, tool details, top tool names etc)
  - Alerts for Cohere (errors, request per model and response time)
summary: |
  Integrate with New Relic to enhance the performance of your Cohere applications and get comprehensive application monitoring and optimization.
icon: logo.png
level: New Relic
authors:
  - New Relic
  - Ramana Reddy
title: Cohere
documentation:
  - name: Cohere integration documentation
    description: |
     Integrate your Cohere with New Relic to get your data into New Relic.
    url: https://github.com/newrelic/nr-openai-observability
dataSourceIds:
  - langchain
dashboards:
  - langchain
alertPolicies:
  - langchain
keywords:
  - mlops
  - cohere