id: cacti
displayName: Cacti
description: |
  This integration will configure Cacti to send Logs to New Relic.
icon: logo.png
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/logs/forward-logs/enable-log-management-new-relic/
keywords:
  - Cacti
  - logs