slug: mosaicml
description: |
  ## Why monitor MosaicML?
  By monitoring MosaicML is essential for training loss, training accuracy, validation loss, validation accuracy, training time.
  
  ## Comprehensive monitoring quickstart for MosaicML
  Monitoring MosaicML helps you ensure that your models are training and performing as expected, track their progress over time, identify potential bottlenecks, troubleshoot problems, and comply with regulations.
  
  ## What’s included in this quickstart?
  New Relic MosaicML monitoring quickstart provides quality out-of-the-box reporting:
  - Dashboards (average tokens, LLM completion's details, chain's details, tool details, top tool names etc)
  - Alerts for MosaicML (errors, request per model and response time)
summary: |
  Integrate with New Relic to get comprehensive application monitoring and optimization for your MosaicML applications.
icon: logo.png
level: New Relic
authors:
  - New Relic
  - Ramana Reddy
title: MosaicML
documentation:
  - name: MosaicML integration documentation
    description: |
     Integrate your MosaicML with New Relic to get your data into New Relic.
    url: https://github.com/newrelic/nr-openai-observability
dataSourceIds:
  - langchain
dashboards:
  - langchain
alertPolicies:
  - langchain
keywords:
  - mlops
  - mosaicML
  - artificial intelligence
  - ai
  - machine learning
  - ML