slug: xgboost
description: |
  ## Why monitor XGBoost?
  Monitoring XGBoost workflows and applications is essential for ensuring the performance, reliability, scalability, and continuous improvement of machine learning applications.
  
  ## Comprehensive monitoring quickstart for XGBoost
  XGBoost tracks various aspects of your model training process, resource utilization, and model performance.
  
  ## What’s included in this quickstart?
  New Relic XGBoost monitoring quickstart provides quality out-of-the-box reporting:
  - Performance optimization: Identify performance bottlenecks, inefficiencies, and areas for improvement in your dmlcXGBoost-based machine learning models
  - Resource management: Monitoring helps ensure efficient use of CPU, memory, and GPU resources, preventing resource contention and optimizing infrastructure utilization
  - Error detection and debugging: Monitoring captures and logs errors, exceptions, and unexpected behavior during model training and inference
  - Security and compliance: Monitoring helps detect unusual or suspicious activity in your machine learning applications, contributing to data security and regulatory compliance efforts
  - Hyperparameter tuning: Tracking model evaluation metrics and training progress metrics allows you to fine-tune hyperparameters and optimize your dmlcXGBoost models for better performance

summary: |
  Integrate your XGBoost applications with New Relic to monitor and optimize their performance.
icon: logo.png
level: New Relic
authors:
  - New Relic
  - Ramana Reddy
title: XGBoost
documentation:
  - name: XGBoost integration documentation
    description: |
     Implement monitoring and instrumentation for your XGBoost, and ensure that your XGBoost data is integrated into New Relic for effective performance analysis and insights.
    url: https://github.com/newrelic-experimental/ml-performance-monitoring
dataSourceIds:
  -  bring-your-own-data
keywords:
  - dmlcXGBoost
  - XGBoost
  - Machine Learning Library
  - dmlc
